services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    expose:
      - 9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TRUSTED_ORIGINS=portainer.local
    restart: unless-stopped
    networks:
      - main
volumes:
  data:
networks:
  main:
    name: portainer_network