services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: main
    volumes:
      - db:/data/postgres
    expose:
      - 5432
    networks:
      - main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 60s
      timeout: 10s
      retries: 5
networks:
  main:
    name: postgres_network
    driver: bridge

volumes:
  db:
